### ISSUE TITLE
Ways to indicate report source files

### ISSUE THREAD

**Issue by thibautjombart** [tjtnew/reportfactory#1]
Currently, the `reports` argument in `compile_reports()` takes a regular expression to be matched against the output of `list_reports()`. It may be useful to implement `integer` and `logical` types, e.g.

```r
# compile the first 3 reports returned by `list_reports(f)`
compile_reports(f, 1:3)

# compile all reports execpt the 2nd one returned by `list_reports(f)`
compile_reports(f, -2)

# compile only reports 2, 4, 6, ... returned by `list_reports(f)`
compile_reports(f, c(FALSE, TRUE))

# compile all reports
compile_reports(f, TRUE)

```

**Comment by tjtnew** [comment]
maybe but I wonder if that's a little obscure.  This is more explicit:

**Comment by tjtnew** [comment]
Closed in https://github.com/tjtnew/reportfactory/commit/8637b6dc48945c4bbe5dbd9306382f8320f969f8
